# Generated by Django 3.2.7 on 2021-10-10 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0003_item_is_sell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=100, verbose_name='Порядок')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('name_slug', models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Название')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='is_ordered',
            field=models.BooleanField(default=False, verbose_name='Заказана?'),
        ),
        migrations.AddField(
            model_name='item',
            name='left',
            field=models.IntegerField(default=0, verbose_name='Остаток'),
        ),
        migrations.AddField(
            model_name='item',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Тираж'),
        ),
        migrations.AddField(
            model_name='item',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='Item.collection'),
        ),
    ]
