# Generated by Django 3.2.7 on 2021-09-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_mob',
            field=models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='Баннер мобильный'),
        ),
    ]
