# Generated by Django 3.2.7 on 2022-01-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='form', verbose_name='Баннер'),
        ),
    ]
