# Generated by Django 3.2.7 on 2022-01-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_returnform_storeform'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='email'),
        ),
    ]
