# Generated by Django 3.2.7 on 2022-01-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_contactform_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeform',
            name='is_in_store',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeform',
            name='is_return_store',
            field=models.BooleanField(default=False),
        ),
    ]
