# Generated by Django 3.2.7 on 2022-02-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20220127_1837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterModelOptions(
            name='contactform',
            options={'verbose_name': 'Форма обратной связи', 'verbose_name_plural': 'Формы обратной связи'},
        ),
        migrations.AlterModelOptions(
            name='returnform',
            options={'verbose_name': 'Запрос на возврат', 'verbose_name_plural': 'Запросы на возврат'},
        ),
        migrations.AlterModelOptions(
            name='storeform',
            options={'verbose_name': 'Запрос на заклад', 'verbose_name_plural': 'Запросы на заклад'},
        ),
        migrations.AddField(
            model_name='contactform',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnform',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeform',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
