# Generated by Django 3.2.7 on 2022-02-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20220202_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnform',
            name='item',
        ),
        migrations.RemoveField(
            model_name='returnform',
            name='user',
        ),
        migrations.RemoveField(
            model_name='storeform',
            name='item',
        ),
        migrations.RemoveField(
            model_name='storeform',
            name='user',
        ),
        migrations.DeleteModel(
            name='ContactForm',
        ),
        migrations.DeleteModel(
            name='ReturnForm',
        ),
        migrations.DeleteModel(
            name='StoreForm',
        ),
    ]
