# Generated by Django 3.2.7 on 2022-02-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20220202_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Заголовок'),
        ),
    ]
