# Generated by Django 3.2.7 on 2022-02-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20220203_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Текст на кнопке'),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_url',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Внутренний URL (/gallery)'),
        ),
    ]
