# Generated by Django 3.2.7 on 2022-01-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_transaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_summ_add',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_summ',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
