# Generated by Django 3.2.7 on 2022-01-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220126_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pay_summ',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
