# Generated by Django 3.2.7 on 2022-01-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_total_in_localstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_in_store',
            field=models.IntegerField(default=0, verbose_name='Заложено карнит'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_in_localstore',
            field=models.IntegerField(default=0, verbose_name='На хранении'),
        ),
    ]
