# Generated by Django 3.2.7 on 2022-02-01 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20220127_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='icons')),
            ],
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.paymenttype'),
        ),
    ]
