# Generated by Django 3.2.7 on 2022-02-01 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20220201_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttype',
            options={'verbose_name': 'Платежная система', 'verbose_name_plural': 'Платежные системы'},
        ),
        migrations.AlterModelOptions(
            name='withdrawalrequest',
            options={'verbose_name': 'Запрос на вывод', 'verbose_name_plural': 'Запросы на вывод'},
        ),
    ]
