# Generated by Django 3.2.7 on 2021-11-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_auto_20211101_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_pay',
            field=models.BooleanField(default=False, verbose_name='Оплачен'),
        ),
    ]
