# Generated by Django 3.2.7 on 2022-01-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_order_is_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_in_store',
            field=models.BooleanField(default=False, verbose_name='Заложено? '),
        ),
    ]
