# Generated by Django 3.2.7 on 2022-01-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0009_auto_20220126_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='your_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
