# Generated by Django 3.2.7 on 2022-01-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0010_auto_20220126_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_in_localstore',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_in_localstore',
            field=models.BooleanField(default=False, verbose_name='Хранение? '),
        ),
    ]
